# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 15:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20180808_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id_client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.Client'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='id_moderateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
