# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-08 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20180808_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='categorie',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='photo',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
